### ISSUE TITLE
build/install script installs package with incorrect name

### ISSUE THREAD

**Issue by courtneecupcakes** [Mechazawa/whatbetter-crawler#2]
Incorrect, or at least inconsistent with the readme, which states to use "whatbetter" to run the program. Actually, you need to use "whatbetter.py" to run it, which is a little confusing.

Relavant install script output: 
```
Processing whatbetter-1.2-py2.7.egg
Copying whatbetter-1.2-py2.7.egg to /usr/lib/python2.7/site-packages
Adding whatbetter 1.2 to easy-install.pth file
Installing whatbetter.py script to /usr/bin
```

And after installing:
```
 ~]$ ls /usr/bin | grep whatbetter
whatbetter
whatbetter.py
```

The entry "whatbetter" was leftover from my previous version of the script I got off bitbucket, and "whatbetter.py" is this one.

**Comment by Mechazawa** [comment]
Fixed by #3
